general:
  appUrl: 'http://localhost:8080/admin'
  appSubTitle: null
  profilePictureUrl: null
  athlete:
    birthday: '1989-08-14'
    maxHeartRateFormula: 'fox'
    heartRateZones:
      mode: relative
      default:
        zone1:
          from: 50
          to: 60
        zone2:
          from: 61
          to: 70
        zone3:
          from: 71
          to: 80
        zone4:
          from: 81
          to: 90
        zone5:
          from: 91
          to: null 
    weightHistory:
      "2020-01-01": 70
    ftpHistory:
      cycling: []
      running: []
appearance:
  locale: 'en_US'
  unitSystem: 'metric'
  timeFormat: 24
  dateFormat:
    short: 'd-m-y'
    normal: 'd-m-Y'
  dashboard:
    layout: null
  heatmap:
    polylineColor: '#fc6719'
    tileLayerUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
    enableGreyScale: true
  photos:
    hidePhotosForSportTypes: []
    defaultEnabledFilters:
      sportTypes: []
      countryCode: null  
  sportTypesSortingOrder: []  
import:
  numberOfNewActivitiesToProcessPerImport: 250
  sportTypesToImport: []
  activityVisibilitiesToImport: []
  skipActivitiesRecordedBefore: null
  activitiesToSkipDuringImport: []
  optInToSegmentDetailImport: false
metrics:
  eddington:
    - label: 'Ride'
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Run'
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Walk'
      showInNavBar: false
      showInDashboardWidget: false
      sportTypesToInclude: ['Walk', 'Hike']
gear:
    stravaGear: []
    customGear: []
zwift:
  level: null
  racingScore: null
integrations:
  notifications:
    services: []
  ai:
    enabled: false
    enableUI: false
    provider: 'ollama'
    configuration:
      key: 'null'
      model: 'null'
      url: 'http://host.docker.internal:11434/api'
daemon:
  cron:
    - action: 'importDataAndBuildApp'
      expression: '0 14 * * *'
      enabled: true
    - action: 'gearMaintenanceNotification'
      expression: '0 14 * * *'
      enabled: false
    - action: 'appUpdateAvailableNotification'
      expression: '0 14 * * *'
      enabled: false
